services:
  db:
    image: postgres:16
    container_name: matchapi-db
    restart: always
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  matchapi:
    build: .
    container_name: matchapi
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matchdb
    ports:
      - "8081:8081"

volumes:
  pgdata:
